### ISSUE TITLE
how does this library work in browsers which doesn't support web worker?

### ISSUE THREAD

**Issue by yutro** [developit/greenlet#14]

**Comment by TomasHubelbauer** [comment]
`Worker` is assumed to be present and there is [no feature detection](https://github.com/developit/greenlet/blob/master/greenlet.js#L7), so you either polyfill it or it doesn't.

**Comment by yutro** [comment]
thanks!

**Comment by MattSidor** [comment]
Thankfully, Web Workers have been around for a while and are pretty broadly supported. IE10+ supports them.

https://caniuse.com/#feat=webworkers

If you still need to support older browsers, you can just check for the presence of `window.Worker`:

    if (window.Worker) {
        ...
    } else {
        ...
    }

**Comment by developit** [comment]
Might be worth adding a section noting that to the readme if anyone wants to PR!

**Comment by developit** [comment]
It may also be possible to polyfill via [jsdom-worker](https://github.com/developit/jsdom-worker).
