### ISSUE TITLE
Too many levels of indentation

### ISSUE THREAD

**Issue by tbodt** [developit/greenlet#17]
The deepest line has 8 levels of indentation, which is honestly way too many. I'd suggest building the web worker code string in a variable, then simply do `new WebWorker(URL.createObjectURL(new Blob([code])))`. Then you'd be down to 4 levels.

**Comment by TrySound** [comment]
@tbodt Indentation where?

**Comment by tbodt** [comment]
In greenlet.js. #18

**Comment by developit** [comment]
I'm fine with splitting things up as long as there is no size impact (if Uglify will collapse the single-use variables).
