### ISSUE TITLE
Add caveat about the scope not being available?

### ISSUE THREAD

**Issue by matthewp** [developit/greenlet#2]
Should the readme add a caveat section perhaps? I think people will try to do stuff like

```js
import greenlet from 'greenlet';
import doStuff from './do-stuff';

let task = greenlet(async () => {
  return await doStuff();
});

task(); // doStuff is not defined
```

There are similar libraries on github that point this out like https://github.com/arqex/worker-function

**Comment by developit** [comment]
Definitely!

**Comment by developit** [comment]
done!
