### ISSUE TITLE
Refused to create a worker from blob

### ISSUE THREAD

**Issue by JCKodel** [developit/greenlet#24]
Refused to create a worker from 'blob:http://localhost:8080/87c22970-8fee-44d9-982e-00aafe130b22' because it violates the following Content Security Policy directive: "default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: gap: content:". Note that 'worker-src' was not explicitly set, so 'default-src' is used as a fallback.

Current content security policy: `default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: gap: content:`

I don't have the slightest idea of how content security policy works, so, it would be nice some light in the README.md =)

**Comment by sylvaindumont** [comment]
@JCKodel you have to add `worker-src blob:` to your csp header and `script-src blob:` as a fallback.
But If you want to keep it simple just add `blob:` at the end of your `default-src`

**Comment by developit** [comment]
@sylvaindumont want to PR that into the README?

**Comment by sylvaindumont** [comment]
sure #28

**Comment by developit** [comment]
Update: I've switched Greenlet over to use Data URIs. Should we update #28?

**Comment by developit** [comment]
Thanks, merged the PR!

**Comment by cochiseruhulessin** [comment]
Whats the point of using CSP if this is the solution?
