### ISSUE TITLE
Edge issue. SCRIPT5022: SecurityError

### ISSUE THREAD

**Issue by sergeyschegolev** [developit/greenlet#34]
Hi guys. Have tried to use greenlet for my project but got security error in the Microsoft Edge(40.15063.674.0).
![security_error](https://user-images.githubusercontent.com/31923498/41401072-8bd21a3e-6fc7-11e8-891e-340d7af80a0d.jpg)
Any help would be very appreciated!

Thanks in advance

**Comment by optimusway** [comment]
Seems the same issue in the Safari, ver 11.1.1
Here is the error i receive `SecurityError: The operation is insecure.`

i tried with the sample from README. Here  it is https://repl.it/@optimusway/greenlet

**Comment by developit** [comment]
I believe this is caused by CSP.

Is it possible the error goes away using [greenlet@0.1.2](https://github.com/developit/greenlet/releases/tag/0.1.2) instead of the current version?

**Comment by jamsesso** [comment]
Just wanted to add to this thread, but I ended up doing something like this:

```
import greenlet from 'greenlet';

export function safeGreenlet(f) {
  try {
    return greenlet(f);
  } catch (e) {
    console.warn('Error creating a worker, degrading experience:', e);
    return f;
  }
}
```

This might not be an appropriate solution for others.

**Comment by spkellydev** [comment]
I've issues a pull request for this issue, but in the meantime if anyone needs a quick fix https://www.npmjs.com/package/greenlet-with-edge
