### ISSUE TITLE
Generator functions

### ISSUE THREAD

**Issue by Ayc0** [developit/greenlet#35]
Is it possible to support generator functions in addition to async functions?

**Comment by developit** [comment]
Yes, and I really want to get this supported!

If you or anyone coming across this wants to try implementing it in Greenlet, I'd be delighted to work with you to get it merged.

**Comment by philosaf** [comment]
Could you describe expected usage of generators with code examples, please?

**Comment by DCtheTall** [comment]
I'd be happy to take a swing at this.

I assume it will always return an instance of a `AsyncGeneratorFunction`?

**Comment by developit** [comment]
Whoops, sorry for the slow reply! Yes this would coerce the main thread to an async generator, regardless of whether it is synchronous or asynchronous.

**Comment by johnsonjo4531** [comment]
@Ayc0 @DCtheTall @developit hey, I made an attempt at this. Feel free to review.  Hope you don't mind I took a shot at it 😅. I just was thinking about how useful this could be, and I also wanted to try and use it in a project, so I was hoping it would come sooner rather than later!
