### ISSUE TITLE
Cannot use spread operator

### ISSUE THREAD

**Issue by syu93** [developit/greenlet#55]
# Issue
Hi, I've been following your work on this project since the beginning and now I'm ready to give it a try.

I'm using `greenlet` inside my Vue 2 application and in one particular case I've the following error : 

```
Uncaught (in promise) ReferenceError: [_PATH_]_node_modules_babel_runtime_helpers_esm_objectSpread2__WEBPACK_IMPORTED_MODULE_2__ is not defined
```

It's seems it miss a dependency to transpile the spread operator. I don't know if it is a Vue specific issue or something more global

## Sep to reproduce

Inside a vue compoenent :

```js
import greenlet from 'greenlet';

const fnSomeWorkerAction = greenlet((itemsToWorkWith) => {
  return itemsToWorkWith.map((item) => {
    return {
      ...item,
    };
  });
});

export default {
  data() {
    items: Array.from(Array(100)).map((item, idx) => ({ id: idx, name: `Plop ${idx}` }),
    fnSomeWorkerAction
  },
  mounted() {
    this.fnSomeWorkerAction(this.items);
  }
}
```

**Comment by developit** [comment]
This is a Vue issue. Don't transpile to helpers when using Greenlet, that isn't supported.
